[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
description = "Adds Scp966 as a monster in Lethal company"
websiteUrl = "https://github.com/FelixAllard/SCP966LC"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
TheWeavers-LethalBestiary = "1.2.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/ProjectSCP.SCP966.dll"
target = "plugins/Scp966/"

[[build.copy]]
source = "../../SCP966/AssetBundles/StandaloneWindows/scp966modassets"
target = "plugins/Scp966/"

[[build.copy]]
source = "./PictureThunderstorePage/Chilling.png"
target = "PictureThunderstorePage/"
[[build.copy]]
source = "./PictureThunderstorePage/CreepyWalk.png"
target = "PictureThunderstorePage/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
# Get the list of categories from https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "bepinex", "clientside", "serverside", "monsters", "mods", ]